//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.27 at 01:43:19 AM IST 
//


package com.noesis.push.api.xml.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.noesis.push.api.xml.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.noesis.push.api.xml.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlPushRequest }
     * 
     */
    public XmlPushRequest createXmlPushRequest() {
        return new XmlPushRequest();
    }

    /**
     * Create an instance of {@link XmlPushRequest.Data }
     * 
     */
    public XmlPushRequest.Data createXmlPushRequestData() {
        return new XmlPushRequest.Data();
    }

    /**
     * Create an instance of {@link XmlPushRequest.Data.RecipientList }
     * 
     */
    public XmlPushRequest.Data.RecipientList createXmlPushRequestDataRecipientList() {
        return new XmlPushRequest.Data.RecipientList();
    }

    /**
     * Create an instance of {@link XmlPushRequest.Data.Message }
     * 
     */
    public XmlPushRequest.Data.Message createXmlPushRequestDataMessage() {
        return new XmlPushRequest.Data.Message();
    }

    /**
     * Create an instance of {@link XmlPushRequest.Data.RecipientList.Recipient }
     * 
     */
    public XmlPushRequest.Data.RecipientList.Recipient createXmlPushRequestDataRecipientListRecipient() {
        return new XmlPushRequest.Data.RecipientList.Recipient();
    }

}
